### ISSUE TITLE
Valentine's to-do list

### ISSUE THREAD

**Issue by ValentineHerr** [EcoClimLab/ForestGEO-tree-rings#30]
I pushed the GLS results (including Scotty Creek since this approach is much faster), but there is few things that I eventually want to get to:

- [x] check the difference between ns(clim, 2) and poly(clim,2).
- [ ] try to fit a glm with log link (or equivalent) instead of log-transforming the response.
- [x] run with most up to date climate data (easy, will probably launch that tonight)
- [x] figure out why levelplots (AIC weights plots) are blank when they are first saved. (they used to be working fine... probably some sneaky  glitch in my code)
- [x] run new sites
- [x]  deal with dbh. no dbh, AGB etc... different  models (but dendro repo needs work before that, since I think it is best if the dbh reconstruction happens there).
